repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: semgrep
        name: Semgrep Security Scan
        entry: semgrep scan --error --config shopping-assistant/.semgrep/rules.yaml
        language: system
        types: [python]
